version: '3'
services:
 dind:
  build: .
  image: deviny/dlaravel_test:latest
  container_name: "dind"
  volumes:
  - ./dlaravel:/dlaravel
  networks:
    - dlaravel_net
  privileged: true
  

networks:
    dlaravel_net:
